language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.4.8

install:
  - pip install -q $DJANGO coverage==3.6 --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - coverage run --source=django_iban ./manage.py test
  - coverage report -m

after_success:
  - pip install coveralls==0.1.1 --use-mirrors
  - coveralls
