language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO_VERSION=1.6.2
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.4.10

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.10
    - python: "3.3"
      env: DJANGO_VERSION=1.4.10

install:
  - pip install -q django==$DJANGO_VERSION coverage==3.6 --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - coverage run --source=django_iban ./manage.py test
  - coverage report -m

after_success:
  - pip install coveralls==0.1.1 --use-mirrors
  - coveralls
