language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.5.1
  - DJANGO=django==1.4.5

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - python setup.py test
